# xcmemory_interest 配置文件
# 由启动脚本自动生成，请勿手动删除 api_key（否则需重新生成）

[server]
database_root = './data/xcmemory'
host = '0.0.0.0'
port = 8080
ws_port = 8081

[lifecycle_manager]
infinity = 999999
short_term_cap = 604800
long_term_cap = 2592000
transition_cap = 31536000
min_scale = 0.1

[netapi]
guid = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11'
max_websocket_frame_size = 65536

[admin]
api_key = 'xi-admin-i60v1a2Ytrqa4GWh6JSvwg7WZOjzxJ0lBGZFDHoY-LI'