# -*- coding: utf-8 -*-
"""
提示词集中管理模块 (Prompts)

将所有 LLM 提示词模板集中于此，与业务逻辑分离。
"""

from .nl import (
    INTENT_CLASSIFY_PROMPT,
    PRE_RETRIEVAL_SYSTEM,
    USER_PROMPT_TEMPLATE,
    NL_TO_MQL_PROMPT,
    NL_TO_SLOTS_PROMPT,
    SUFFICIENCY_PROMPT,
    QUERY_REWRITE_PROMPT,
    RANKER_PROMPT,
    WRITE_MQL_PROMPT,
    RESULT_GENERATION_PROMPT,
    REFLECTION_REVIEW_PROMPT,
    REGENERATE_MQL_PROMPT,
)

from .chat import (
    QUERY_GEN_PROMPT,
    PARAPHRASE_PROMPT,
    EXTRACT_FACTS_PROMPT,
    ROLEPLAY_SYSTEM_TEMPLATE,
)

__all__ = [
    "INTENT_CLASSIFY_PROMPT",
    "PRE_RETRIEVAL_SYSTEM",
    "USER_PROMPT_TEMPLATE",
    "NL_TO_MQL_PROMPT",
    "NL_TO_SLOTS_PROMPT",
    "SUFFICIENCY_PROMPT",
    "QUERY_REWRITE_PROMPT",
    "RANKER_PROMPT",
    "WRITE_MQL_PROMPT",
    "RESULT_GENERATION_PROMPT",
    "REFLECTION_REVIEW_PROMPT",
    "REGENERATE_MQL_PROMPT",
    "QUERY_GEN_PROMPT",
    "PARAPHRASE_PROMPT",
    "EXTRACT_FACTS_PROMPT",
    "ROLEPLAY_SYSTEM_TEMPLATE",
]
